### ISSUE TITLE
[please add] Extra Alchemy

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/Dragons-of-Twilight#12]
https://www.curseforge.com/minecraft/mc-mods/extra-alchemy

This mod adds more potions to the game, along with potion accessories
![image](https://66.media.tumblr.com/avatar_9b6b462a7b5d_128.pnj)
Some of its features include a potion bag for better storage, potion combining and splitting [same type only, for balance reasons], and vial forms of potions so that you can stack potions.

The potions do not seem to clash with Edge of Twilight's core gameplay.

**Comment by kreezxil** [comment]
nope, definitely no, again 4 magic mods, let's use them.
