### ISSUE TITLE
[please add] inventory pets

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/Dragons-of-Twilight#13]
https://www.curseforge.com/minecraft/mc-mods/inventory-pets

It's an item, it's a pet, it's an... inventory pet!
This mod adds nifty craftable inventory "pets" that have special abilities in exchange for feeding them certain items.

As an example,
![](https://web.archive.org/web/20170804205223im_/http://www.creeptech.net/images/ip/recipes/juggernaut-rec.png)
Juggernaut 
Shield Wall [Right Click]
Food: Obsidian Nugget
Eats: Every 3 uses
Notes: 2 minute cooldown between uses

All of the pets are mid-late game, since they require high tier items such as diamonds or nether stars. The current webpage in the curseforge site doesn't work, so here's a [link](https://web.archive.org/web/20170804205223/http://www.minecraftforum.net:80/forums/mapping-and-modding/minecraft-mods/2402467-inventory-pets-animated-creatures-that-live-in) that shows further features of the mod.

**Comment by Draconian4466** [comment]
This mod is pretty fun but dissable the illuminati pet as it can give you anything

**Comment by kreezxil** [comment]
not gonna add it, we got 4 magic mods and portable crafting and we don't need something that complicates matters.
