### ISSUE TITLE
[please add] Recurrent Complex

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/Dragons-of-Twilight#14]
https://www.curseforge.com/minecraft/mc-mods/recurrent-complex

Since the overworld is getting left in and mystcraft will generate even more worlds, this mod would be a nice companion as it adds random structures to each of the worlds. The mod does not add any new ore or block gen, only structure gen, so it doesn't aesthetically conflict with the existing overworld or other worlds.

**Comment by kreezxil** [comment]
for now i'm going to say no

**Comment by kreezxil** [comment]
also you don't witness the worldgen lag it does to the console
