### ISSUE TITLE
[please fix]The Ur-ghast crashes the server uppon spawning

### ISSUE THREAD

**Issue by Cthuwu** [kreezxil/Dragons-of-Twilight#15]
![World_of_Dragons_1 12 2_2019-08-03_9_59_59_AM](https://user-images.githubusercontent.com/46110723/62412831-47db7a80-b5cd-11e9-98b1-8cb70eff4b75.png)
![World_of_Dragons_1 12 2_2019-08-03_10_00_06_AM](https://user-images.githubusercontent.com/46110723/62412833-490ca780-b5cd-11e9-8c07-9e7027a1a973.png)

**Comment by kreezxil** [comment]
I need the actual crash log not the screen shot of what you think is relevant.
