### ISSUE TITLE
[please fix]Crash with Just enough items

### ISSUE THREAD

**Issue by StarrAnnika** [kreezxil/Dragons-of-Twilight#17]
**Describe the bug**

Mincecraft crashed after using lag goggles and pressing FPS button 
**To Reproduce**
1. Go to '...' Lag Goggles
2. Click on '....' FPS
3. Scroll down to '....' Got the crash after clicking *FPS Button*

**Screenshots**

![ac942af979b3d091c0c4a6fc8bd74f49](https://user-images.githubusercontent.com/53842962/62586719-bf8afd00-b88c-11e9-9cf0-2511eb477f25.png)

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Mod Pack : Edge of Twilight
 - Mod Name: Just Enough Items
 - Mod Version: 4.15.0.287 

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Crash Report: https://paste.dimdev.org/jaruloyamu.mccrash
Debug Log:
Latest Log:

**Additional context**

**Comment by kreezxil** [comment]
https://github.com/mezz/JustEnoughItems/issues/1673

**Comment by kreezxil** [comment]
mezz reports that a safeguard has been installed in JEI to prevent this. Today's update contains this fix. Please test and open another report if it happens again.
