### ISSUE TITLE
Reap Mod doesn't allow Roots/Mystical World crops to be right-clicked

### ISSUE THREAD

**Issue by GrokDuckFarmer** [kreezxil/Dragons-of-Twilight#19]
Playing EoT 1.6.7 and noticed that right-clicking vanilla crops works thanks to the Reap Mod, but the Roots crop (wildroot) and Mystical World crop (aubergine) don't.  I tried added them to the Reap config file like below:

>     S:whitelist <
>         minecraft:potatoes
>         minecraft:carrots
>         minecraft:wheat
>         minecraft:beetroots
>         minecraft:cocoa
>         mysticalworld:aubergine
>         roots:wildroot
>      >

Sadly, this doesn't work.  However, the Simply Harvest mod works like a champ.  I suggest that be added and the Reap mod config edited to remove all the crops.

https://www.curseforge.com/minecraft/mc-mods/simple-harvest

**Comment by kreezxil** [comment]
nice, that was mod I was trying to find but couldn't remember what it was called. I'll switch these mods out for the other on the next update.

**Comment by GrokDuckFarmer** [comment]
Oh, please add the Living Axe to the Reap mod config to allow it to chop down trees.

>     S:allowed_tree_tools <
>         minecraft:wooden_axe
>         minecraft:golden_axe
>         minecraft:stone_axe
>         minecraft:iron_axe
>         minecraft:diamond_axe
>         roots:living_axe
>      >

**Comment by GrokDuckFarmer** [comment]
So, here's what should be done:

1) Add Simple Harvest mod
2) Edit out crops from the S:whitelist section of the Reap mod config
3) Add "roots:living_axe" to the S:allowed_tree_tools section of the Reap mod config
4) Buy yourself a pizza and watch a good movie

**Comment by kreezxil** [comment]
Why should I do all that to Reap mod when Simply Harvest handles it all?

And I'll go back to the chopdown mod I had before, I thought I went back to it already and disabled the reap mod's axing behavior because reap mod didn't even work with normal axes.

**Comment by kreezxil** [comment]
mod removed and other mod restored that chopped down the trees, simply harvest added.
