### ISSUE TITLE
[please add] Magic seeds for Electroblobs Wizardry

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/Dragons-of-Twilight#2]
https://www.curseforge.com/minecraft/mc-mods/magic-seeds-for-electroblobs-wizardry

Reason: This mod allows players to grow crystals needed for Electroblob's Wizardry, and the crystals are common anyway.

However, the Crystal or magic ore does not spawn in the twilight forest, maybe because the level of the ground is too low or because crystal ores don't spawn in the twilight forest.

**Comment by kreezxil** [comment]
added
