### ISSUE TITLE
[please fix] urGhastFireball crashing server

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/Dragons-of-Twilight#22]
Player Wither_gy7 aka Discord User jtapusen#0767 was running around with the electroblob's flying staff when he crashed, though according to the log, i don't think it's the staff causing the crash.

**To Reproduce**
1. Enter the area directed in the crash log - 1361.83, 220.22, -479.06
2. Crash

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838 
 - Mod Pack : Edge of Twilight 1.8.9 
https://www.curseforge.com/minecraft/modpacks/edge-of-twilight/files/2760811
 - Mod Name: Twilight Forest
 - Mod Version: 3.9.984  

Crash Report: https://paste.dimdev.org/netimayaku.rb

**Additional context**
Player reported that the urGhast was extremely laggy in SSP
Meanwhile in the Twilight Forest Discord...
![image](https://user-images.githubusercontent.com/34356883/62920209-e5674480-bd59-11e9-9bd8-30acfaeb9d03.png)
^Discord Username Androsa#5414^

**Comment by kreezxil** [comment]
ok, updating.

also they're retarded, I'm not gonna remove that mod.

**Comment by kreezxil** [comment]
and yeah, i agree with them, you're retarded you should've known from reading the stack trace that modstats was causing the issue.
