### ISSUE TITLE
[please add] Dimensional Doors

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/Dragons-of-Twilight#9]
https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors

Since we're not as worried about the amount of dimensions as world of dragons, this mod will add dimensional dungeons that people can fight in a portable dimension environment.

My only concern is that this mod has options which teleport you back to the overworld, so I don't know how that would work in this modpack.

**Comment by kreezxil** [comment]
No, let's not even consider this for now. I don't want to burgeon that pack right now. I want to know what works and what doesn't and then decide what to keep and what to not keep and finally what to config and not config and then subsequently what to tweak and not tweak leaving you to do quest lines for what remains.
